export const EVENTS_DB = {
  "saienfes14-day1": {
    title: "大阪最宴祭14 1日目 (2026/2/21)",
    startHour: 9,
    endHour: 23,
    stages: [
      {
        id: "room1",
        name: "第1会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room1b",
        name: "第1会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room2",
        name: "第2会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room3",
        name: "第3会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room4",
        name: "第4会議室",
        group: "浪速区民センター2F",
      },
      {
        id: "room5",
        name: "第5会議室",
        group: "浪速区民センター2F",
      },
      {
        id: "japanese",
        name: "和室",
        group: "浪速区民センター2F",
      },
      {
        id: "room6",
        name: "第6会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room7",
        name: "第7会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room8",
        name: "第8会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room9",
        name: "第9会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "rental1",
        name: "カフェ上（大）",
        group: "レンタルスペース※階段のみ",
      },
      {
        id: "rental2",
        name: "カフェ上（大）",
        group: "レンタルスペース※階段のみ",
      },
      {
        id: "room401",
        name: "民泊401",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room403",
        name: "民泊403",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room502",
        name: "民泊502",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room602-1",
        name: "民泊602①",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room602-2",
        name: "民泊602②",
        group: "民泊※エレベーターあり",
      },
      {
        id: "stage1",
        name: "ステージ①",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "stand",
        name: "観客席",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "booth1",
        name: "ホールブース①",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "booth2",
        name: "ホールブース②",
        group: "浪速区民センター1F ホール",
      },
    ],
    schedules: [
      {
        id: 101,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 102,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 103,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 104,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 105,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 106,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "13:50",
        endTime: "14:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 107,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:10",
        endTime: "14:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 108,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:30",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 109,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:50",
        endTime: "15:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 110,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:10",
        endTime: "15:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 111,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 112,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:50",
        endTime: "16:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 113,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:10",
        endTime: "16:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 114,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:30",
        endTime: "17:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 115,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:50",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 116,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "17:30",
        endTime: "18:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 117,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "18:10",
        endTime: "18:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 118,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "18:50",
        endTime: "19:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 119,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "19:30",
        endTime: "20:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 120,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "20:10",
        endTime: "20:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 201,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "10:45",
        endTime: "11:25",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 202,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "11:35",
        endTime: "12:15",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 203,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "12:25",
        endTime: "13:05",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 204,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "13:15",
        endTime: "13:55",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 205,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "14:10",
        endTime: "14:50",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 206,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "15:00",
        endTime: "15:40",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 207,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "15:50",
        endTime: "16:30",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 208,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "16:40",
        endTime: "17:20",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 209,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "17:35",
        endTime: "18:15",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 210,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "18:25",
        endTime: "19:05",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 211,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "19:15",
        endTime: "19:55",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 212,
        stageId: "room2",
        title: "ものだらけVI",
        artist: "TKGデラックス",
        startTime: "20:05",
        endTime: "20:45",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 301,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 302,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "11:30",
        endTime: "12:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 303,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "12:30",
        endTime: "13:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 304,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "13:30",
        endTime: "14:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 305,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "14:30",
        endTime: "15:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 306,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 307,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 308,
        stageId: "room3",
        title: "Rotates",
        artist: "ハテナボックス",
        startTime: "17:30",
        endTime: "18:15",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 401,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 402,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "12:40",
        endTime: "14:10",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 403,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "14:50",
        endTime: "16:20",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 404,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "17:00",
        endTime: "18:30",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 405,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "19:10",
        endTime: "20:40",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 501,
        stageId: "room5",
        title: "銀の弾丸は鈍くつらぬく",
        artist: "スパイシードロップス",
        startTime: "10:30",
        endTime: "12:30",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 502,
        stageId: "room5",
        title: "銀の弾丸は鈍くつらぬく",
        artist: "スパイシードロップス",
        startTime: "13:15",
        endTime: "15:15",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 503,
        stageId: "room5",
        title: "銀の弾丸は鈍くつらぬく",
        artist: "スパイシードロップス",
        startTime: "16:00",
        endTime: "18:00",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 504,
        stageId: "room5",
        title: "銀の弾丸は鈍くつらぬく",
        artist: "スパイシードロップス",
        startTime: "18:45",
        endTime: "20:45",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 601,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 602,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 603,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "13:30",
        endTime: "14:30",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 604,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "15:00",
        endTime: "16:00",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 605,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "16:30",
        endTime: "17:30",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 606,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 607,
        stageId: "japanese",
        title: "池上マスターからの脱出",
        artist: "シングルズ",
        startTime: "19:30",
        endTime: "20:30",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 701,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "10:30",
        endTime: "12:05",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 702,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "12:30",
        endTime: "14:05",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 703,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "14:30",
        endTime: "16:05",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 704,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "16:30",
        endTime: "18:05",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 705,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "18:30",
        endTime: "20:05",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 801,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 802,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "11:40",
        endTime: "12:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 803,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "12:50",
        endTime: "13:50",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 804,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "14:00",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 805,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "15:10",
        endTime: "16:10",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 806,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "16:20",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 807,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "17:30",
        endTime: "18:30",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 808,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "18:40",
        endTime: "19:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 809,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "19:50",
        endTime: "20:50",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 901,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 902,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 903,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "13:20",
        endTime: "14:20",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 904,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 905,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "16:00",
        endTime: "17:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 906,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "17:20",
        endTime: "18:20",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 907,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "18:40",
        endTime: "19:40",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 908,
        stageId: "room8",
        title: "タンクトップバトラー！！袖無",
        artist: "ShareKOBE",
        startTime: "20:00",
        endTime: "21:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1001,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "10:30",
        endTime: "11:40",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1002,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "12:05",
        endTime: "13:15",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1003,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "13:40",
        endTime: "14:50",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1004,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "15:10",
        endTime: "16:20",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1005,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "16:45",
        endTime: "17:55",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1006,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "18:20",
        endTime: "19:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1007,
        stageId: "room9",
        title: "-ひらめき もーしょん-ひっつけ もじつく～る",
        artist: "ナゾトキズナ",
        startTime: "19:50",
        endTime: "21:00",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 1101,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "10:35",
        endTime: "11:45",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 1102,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "13:15",
        endTime: "14:25",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 1103,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "15:55",
        endTime: "17:05",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 1104,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "18:35",
        endTime: "19:45",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 1105,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "21:15",
        endTime: "22:25",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 1201,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "9:20",
        endTime: "10:20",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1202,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1203,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1204,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "17:20",
        endTime: "18:20",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1205,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "20:00",
        endTime: "21:00",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1301,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "9:00",
        endTime: "9:50",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1302,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "10:10",
        endTime: "11:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1303,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "11:20",
        endTime: "12:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1304,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "12:40",
        endTime: "13:30",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1305,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "13:50",
        endTime: "14:40",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1306,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "15:00",
        endTime: "15:50",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1307,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "16:10",
        endTime: "17:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1308,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1309,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1310,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1311,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "21:00",
        endTime: "21:50",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1312,
        stageId: "room401",
        title: "＋PLUS MINUSー",
        artist: "Leia",
        startTime: "22:10",
        endTime: "23:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1401,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1402,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "11:45",
        endTime: "12:45",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1403,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "13:15",
        endTime: "14:15",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1404,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "14:30",
        endTime: "15:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1405,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "15:45",
        endTime: "16:45",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1406,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "17:00",
        endTime: "18:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1407,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "18:30",
        endTime: "19:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1408,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "19:45",
        endTime: "20:45",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1501,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "9:20",
        endTime: "10:05",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1502,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "10:15",
        endTime: "11:00",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1503,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "11:15",
        endTime: "12:00",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1504,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "12:10",
        endTime: "12:55",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1505,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "13:05",
        endTime: "13:50",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1506,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1507,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "14:55",
        endTime: "15:40",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1508,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "15:50",
        endTime: "16:35",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1509,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "16:45",
        endTime: "17:30",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1510,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "17:40",
        endTime: "18:25",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1511,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "18:35",
        endTime: "19:20",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1512,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "19:30",
        endTime: "20:15",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1513,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "20:25",
        endTime: "21:10",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 1601,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "9:20",
        endTime: "10:05",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1602,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1603,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "11:30",
        endTime: "12:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1604,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "12:30",
        endTime: "13:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1605,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "13:30",
        endTime: "14:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1606,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1607,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1608,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "17:30",
        endTime: "18:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1609,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "18:30",
        endTime: "19:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1610,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "19:30",
        endTime: "20:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1611,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "20:30",
        endTime: "21:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1612,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "21:30",
        endTime: "22:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 1701,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1702,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1703,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1704,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1705,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1706,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1707,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1708,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1709,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1710,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "19:30",
        endTime: "20:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1711,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1712,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 1801,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "10:30",
        endTime: "11:45",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1802,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "12:00",
        endTime: "13:15",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1803,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "13:30",
        endTime: "14:45",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1804,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "15:00",
        endTime: "16:15",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1805,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "16:30",
        endTime: "17:45",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1806,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "18:00",
        endTime: "19:15",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1807,
        stageId: "stage1",
        title: "THE LOST CARD",
        artist: "テクニコテクニカ",
        startTime: "19:30",
        endTime: "20:45",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 1901,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1902,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "12:00",
        endTime: "13:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1903,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "13:30",
        endTime: "15:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1904,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "15:00",
        endTime: "16:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1905,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "16:30",
        endTime: "18:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1906,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "18:00",
        endTime: "19:30",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 1907,
        stageId: "stand",
        title: "Letter to You",
        artist: "なぞすぽっと",
        startTime: "19:30",
        endTime: "21:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 2001,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2002,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2003,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2004,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "14:30",
        endTime: "15:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2005,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2006,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2007,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2008,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2009,
        stageId: "booth1",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "19:30",
        endTime: "20:10",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 2101,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "10:30",
        endTime: "10:50",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2102,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "10:55",
        endTime: "11:15",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2103,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "11:20",
        endTime: "11:40",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2104,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "11:45",
        endTime: "12:05",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2105,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "12:10",
        endTime: "12:30",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2106,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:00",
        endTime: "13:20",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2107,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:25",
        endTime: "13:45",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2108,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:50",
        endTime: "14:10",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2109,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "14:15",
        endTime: "14:35",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2110,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "14:40",
        endTime: "15:00",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2111,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:30",
        endTime: "15:50",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2112,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:55",
        endTime: "16:15",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2113,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "16:20",
        endTime: "16:40",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2114,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "16:45",
        endTime: "17:05",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2115,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "17:10",
        endTime: "17:30",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2116,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:00",
        endTime: "18:20",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2117,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:25",
        endTime: "18:45",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2118,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:50",
        endTime: "19:10",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2119,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "19:15",
        endTime: "19:35",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 2120,
        stageId: "booth2",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "19:40",
        endTime: "20:00",
        color: "bg-indigo-100 border-indigo-300",
      },
    ],
  },
  "saienfes14-day2": {
    title: "大阪最宴祭14 2日目 (2026/2/22)※準備中",
    startHour: 9,
    endHour: 23,
    stages: [],
    schedules: [],
  },
  "saienfes14-day3": {
    title: "大阪最宴祭14 3日目 (2026/2/23)※準備中",
    startHour: 9,
    endHour: 23,
    stages: [],
    schedules: [],
  },
};
